frontend/controllers/BookController.php
<?php

namespace frontend\controllers;

use console\models\BookTranslate;
use console\models\City;
use Yii;
use console\models\Book;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Sunra\PhpSimple\HtmlDomParser;
use console\models\BookSearch;
use yii\helpers\ArrayHelper;
/**
 * GrudController implements the CRUD actions for Book model.
 */
class BookController extends Controller
{
    const KEY = "trnsl.1.1.20190304T092450Z.dfe2c2c37b0cb874.6f797bed6a5e208205a59f1adcca18cfd40ee43c"; // testolegkot
    const LANGUAGE = "ru-en";

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

//        $dataProvider = new ActiveDataProvider([
//            'query' => Book::find(),
//        ]);

        $dataProvider->sort->defaultOrder = ['id' => SORT_DESC];

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Book();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }


    public function actionParse($id){

        $model = $this->findModel($id);
        $source = $model->row_html; // источник
        $model->title = $this->getTitle($source);
        $model->price = $this->getPrice($source);
        $model->year = $this->getYear($source);
        $model->condition = $this->getCondition($source);
        $model->seller = $this->getSeller($source);
        $model->seller_city = $this->getSellerCity($source);
        $model->descr = $this->getDescription($source);
        $model->image = serialize(json_encode($this->getImage($source)));
        $model->addition_descr =$this->getAdditionDescr($source);
        $model->izdatel_city =$this->getIzdatelCity($source);
        $model->translate = Book::NON_TRANSALATED;
        $model->updateAttributes(['title','price','year','condition','seller','seller_city','descr','image','addition_descr','translate','izdatel_city']);

        return $this->redirect('view?id='.$id);
    }

    private function getTitle($source){

        $regexp = '~<b>.+\</b>~';

        $match = [];
        if (preg_match($regexp, $source, $match)) {
            //$x= "+ Найдено слово '{$match[0]}'\n";
            //vd($match,false);
            $x = $match[0];
        } else {
            $x= "";
        }

    return trim(strip_tags($x));
    }
    private function getPrice($source){

        $regexp = '~Цена:.+?руб.~m';

        $match = [];
        if (preg_match($regexp, $source, $match)) {
            $x = $match[0];
        } else {
            $x= "";
        }

    return trim(str_replace("руб.","",str_replace("Цена:","",$x)));
    }
    private function getYear($source){
        $regexp = '~[0-9]{4}г\.~';
        $regexp2 = '~[0-9]{4}\s+г\.~';
        $regexp3 = '~[0-9]{4}\(~';
        $match = [];
        if (preg_match($regexp, $source, $match) || preg_match($regexp2, $source, $match) || preg_match($regexp3, $source, $match)) {
            $x = $match[0];
        } else {
            $x= "";
        }
        return trim(str_replace("(","",str_replace("г.","",$x)));
    }
    private function getCondition($source){
        $regexp = '~Состояние:.+?\<~';
        $match = [];
        if (preg_match($regexp, $source, $match)) {
            $x = $match[0];
        } else {
            $x= "";
        }
        return  trim(str_replace("<","",str_replace("Состояние:","",$x)));
    }
    private function getSeller($source){

        $regexp = '~BS.+?<~';
        $match = [];
        if (preg_match($regexp, $source, $match)) {
            $x = $match[0];
        } else {
            $x= "";
        }

        return  urldecode(trim(str_replace("BS -","",str_replace("<","",preg_replace("~BS.+?>~","",$x)))));
    }
    private function getSellerCity($source){
        $regexp = '~a\>,.+?\)~';
        $match = [];
        if (preg_match($regexp, $source, $match)) {
            $x = $match[0];
        } else {
            $x= "";
        }
        return  trim(str_replace(".)","",str_replace("a>,","",$x)));
    }
    private function getDescription($source){
        $regexp = '~/b>.+?[0-9]{2,}.+?с\.~';
        $regexp2 = '~/b>.+?<br~';
        $match = [];
        if (preg_match($regexp, $source, $match) || preg_match($regexp2, $source, $match)) {
            $x = $match[0];
        } else {
            $x= "";
        }
        return  trim(str_replace("<br","",str_replace("/b>","",$x)));
    }
    private function getImage($source){
        $i=0;
        $result= [];
        $source = str_replace("amp;","",$source);
        $regexp = '~http:\/\/www.alib.ru\/foto.php4\?.+?\"~';
        $match = [];
        if (preg_match_all($regexp, $source, $match)) {
            $x = $match;
        } else {
            $x=[];
        }
        if(!empty($x[0])){
            foreach ($x[0] as $row => $item){
                $i++;
                $result[$i] = trim(str_replace("\"","",$item));
            }
        }


        return  $result;
    }
    private function getAdditionDescr($source){

        //vd($source,false);
        $regexp = '~\sс\..+?Состояние~';
        $regexp2 = '~[0-9]{2,}с\..+?Состояние~';
        $regexp3 = '~[0-9]{2,}с.+?Состояние~';
        $regexp4 = '~[0-9]{2,}.c\..+?Состояние~';

        $match = [];
        if ( preg_match($regexp, $source, $match ) || preg_match($regexp2, $source, $match) ||  preg_match($regexp3, $source, $match) || preg_match($regexp4, $source, $match)) {
            $x = $match[0];
        } else {
            $x= "";
        }
        return  '<p>'.trim(preg_replace("~^\.~","",preg_replace("~с\.~","",preg_replace("~[0-9]{1,}.c\.~","",preg_replace("~[0-9]{1,}.c\.~","",preg_replace("~[0-9]{1,}с~","",str_replace("Состояние","",$x))))))).'</p>';



        // мой первый вариант отлично работает
        //*****************************************************************
        //        $pieces =  explode('<br>',$source);
        //        $regexp = '~Состояние~';
        //        $match = [];
        //        if (preg_match($regexp, $pieces[2], $match)) {
        //            $x = $match[0];
        //        } else {
        //            $x= "";
        //        }
        //        return  $pieces[2] &&  empty($x) ? trim($pieces[2]) : false;
        // *************************************************************************
    }


    public function actionTranslate($id){

        $model = $this->findModel($id);

        if( $model->translate == Book::TRANSLATED){
            return $this->redirect(['book-translate/view/?id='.$model->translated->id]);
        }

        $source = $model->row_html; // источник
        $model->title = $this->getTitle($source);
        $model->price = $this->getPrice($source);
        $model->year = $this->getYear($source);
        $model->condition = $this->getCondition($source);
        $model->seller = $this->getSeller($source);
        $model->seller_city = $this->getSellerCity($source);
        $model->descr = $this->getDescription($source);
        $model->image = serialize(json_encode($this->getImage($source)));
        $model->addition_descr =$this->getAdditionDescr($source);
        $model->updateAttributes(['title','price','year','condition','seller','seller_city','descr','image','addition_descr']);

frontend/views/book/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model console\models\Book */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'link_id')->textInput() ?>

    <?= $form->field($model, 'row_html')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'descr')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'seller')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'condition')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'image')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'price')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'year')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/book/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model console\models\BookSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'link_id') ?>

    <?= $form->field($model, 'row_html') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'descr') ?>

    <?php // echo $form->field($model, 'seller') ?>

    <?php // echo $form->field($model, 'condition') ?>

    <?php // echo $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'price') ?>

    <?php // echo $form->field($model, 'year') ?>

    <?php // echo $form->field($model, 'xml_file_name') ?>

    <?php // echo $form->field($model, 'seller_city') ?>

    <?php // echo $form->field($model, 'addition_descr') ?>

    <?php // echo $form->field($model, 'izdatel_city') ?>

    <?php // echo $form->field($model, 'translate') ?>

    <?php // echo $form->field($model, 'translate_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/book/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model console\models\Book */

$this->title = Yii::t('app', 'Create Book');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Books'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/book/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Книги');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [

            'id',
            [
                'label' => 'Посмотреть',
                'format' => 'raw',
                'contentOptions' => ['class' => 'col-md-1','style' => 'vertical-align:middle;'],
                'value' => function ($model) {
                    if($model->link){
                        $out =  Html::a('Код ссылки','/links/view/?id='.$model->link->id,['class'=> 'btn btn-default']) .'<br>'. Html::a('Alib.ru', $model->link->href,['class'=> 'btn btn-info','style'=>'margin-top:10px','target'=>'_blank']);
                        return $out;
                    }
                }
            ],
            'row_html:html',
            //'title',
            //'descr',
            //'seller',
            //'condition',
            //'image',
            //'price:ntext',
            //'year:ntext',

            [
                'header'=>'Действия',
                'contentOptions' => ['class' => 'col-md-1','style' => 'vertical-align:middle;'],
                'class' => 'yii\grid\ActionColumn',
                'template' => '{translate}{update}{view}{delete}',
                'buttons' => [
                    'translate' => function ($url,$model) {
                            return Html::a(' Перевести', $url, ['class' => 'btn btn-warning ', 'style' => 'display:block;margin-bottom: 5px;width:120px;']);
                    },
                    'update' => function ($url,$model) {
                            return Html::a(' Редактировать', $url, ['class' => 'btn btn-primary ', 'style' => 'display:block;margin-bottom: 5px;width:120px;']);
                    },
                    'view' => function ($url,$model) {
                              return Html::a(' Просмотр', $url, ['class' => 'btn btn-info ', 'style' => 'display:block;margin-bottom: 5px;width:120px;']);
                    },
                    'delete' => function ($url,$model) {

                             return Html::a(' Удалить', $url,
                                 [
                                     'class' => 'btn btn-danger ',
                                     'data-method' => 'post',
                                     'data-confirm' => Yii::t('yii', 'Вы уверены?'),
                                     'style' => 'display:block;width:120px;'
                                 ]);

                    },

                ],
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

<style>
    td {
        max-width: 500px;
        white-space: normal !important;
        overflow: hidden;
    }
    .centred{
        vertical-align:middle;
    }
</style>

frontend/views/book/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model console\models\Book */

$this->title = Yii::t('app', 'Update Book: {name}', [
    'name' => $model->title,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Books'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="book-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/book/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model console\models\Book */

$this->title = $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Книги'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="book-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Редактировать'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Удалить'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a(Yii::t('app', 'Alib.ru'),  $model->link->href, ['class' => 'btn btn-default','target'=> '_blank']) ?>
        <?= Html::a(Yii::t('app', 'Распарсить'), ['parse', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
        <?= Html::a(Yii::t('app', 'Перевести'), ['/book/translate', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>

    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            //'link_id',
            [   'format'=> 'raw',
                'label' => 'Ссылка',
                'value' => Html::a($model->link->href,$model->link->href,['target'=>'_blank'])
            ],
            //'row_html:ntext',
            [
                'label' => 'HTML',
                'format'=> 'html',
                'value' => $model->row_html,
            ],
            'title',
            'descr',
            'addition_descr:html',
            'izdatel_city',
            'seller',
            'seller_city',
            'condition',

            [
                'label' => 'Картинки',
                'format'=> 'html',
                'value' => function($model){
                    $resultHtml= '';
                    $a = json_decode(unserialize($model->image));

                    if($a){
                        foreach ( $a as $image ){
                            $resultHtml .= '<a href="'.$image.'">'.$image.'</a>';
                        }
                    }

                    return $resultHtml;
                }
            ],
            'price:ntext',
            'year:ntext',
        ],
    ]) ?>

</div>
<style>
    td {
        max-width: 500px;
        white-space: normal !important;
        overflow: hidden;
    }
</style>